CREATE TABLE IF NOT EXISTS t_pay_product (
  id int(20) NOT NULL AUTO_INCREMENT,
  product_name VARCHAR(64) NOT NULL,
  product_type TINYINT NOT NULL,
  state TINYINT(6) NOT NULL DEFAULT 1,
  agent_rate DECIMAL(20,6) NOT NULL DEFAULT 0,
  mch_rate DECIMAL(20,6) NOT NULL DEFAULT 0,
  created_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

